services:
  frontend:
    build:
      context: ./frontend
      target: frontend-builder  # explicitly named target stage
    image: frontend-builder

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - frontend